### ISSUE TITLE
Allow array as input in rescues:addquote

### ISSUE THREAD

**Issue by dewiniaid** [FuelRats/api.fuelrats.com#102]
I was under the impression that the methods for appending quotes were going to allow an array of quotes to be submitted rather than an individual quote.

This is useful, because Mecha will occasionally inject informational quotes of its own in addition to user-submitted input -- namely data reporting when it auto*correct*ed a system (including the original name) and when it auto*detect*ed a system.  While these events are likely a small portion of traffic overall, being able to append both quotes in one request rather than two would be beneficial.

**Comment by xlexi** [comment]
Feature request accepted, marked as high priority issue
