### ISSUE TITLE
rats:read reports incorrect rescue counts

### ISSUE THREAD

**Issue by dewiniaid** [FuelRats/api.fuelrats.com#107]
Searching for myself on the live API (using the websocket interface, but it shouldn't matter) yields (edited for brevity):
```
{
"CMDRname":"Dewin",
"rescueCount":11,
"successfulAssistCount":0,
"successfulRescueCount":22,
"_id":"56d4f253cf7648e27c858799",
"score":6.2857385
}
```
I haven't actually done much in the way of rescues -- I think I have 5 legitimate rescues to my name and I'm not certain any of the 11 linked here are mine.  But I'm listed with 11 rescues and 22 successful rescues?

**Comment by trezy** [comment]
Closing because this happened during maintenance.
