### ISSUE TITLE
Proposed Implementation of nick search convenience API

### ISSUE THREAD

**Issue by xlexi** [FuelRats/api.fuelrats.com#149]
Proposal to solve current issues with matching inaccurate nicknames with rats

__Syntax:__ GET /nickname/search?q=[nickname]

Input: An IRC nickname with brackets stripped.
Output: A list of matching Users, sorted by a case insensitive Levenshtein distance approximation.    
     
This will require the use of the postgres [citext](https://www.postgresql.org/docs/9.1/static/citext.html) module and will have to be a separate endpoint from the currently used Users?nicknames endpoint to prevent a performance impact on unrelated queries.     
    
@Marenthyu

**Comment by Marenthyu** [comment]
Im ok with that and willing to adapt the bot to that. :3

**Comment by xlexi** [comment]
Beginning implementation in fuelrats/api.fuelrats.com/citext

**Comment by xlexi** [comment]
Details on implementation:    
Endpoint will be /nickname/search/:nickname
*(Example: /nickname/search/xlexious)*
Nickname can be encoded with standard RFC 3986 url encoding.
   
The API will strip out [brackets] and perform a search for both the original nickname and without brackets.   

The endpoint will be publically accessible and require no authentication, the result will be an array of matching user objects.   
the email field of the user object will be null if the request is unauthenticated or does not have the privileges to view this user.   
   
the rats of the user will be returned as an array of rat **objects** in the field **rats**    
It will not be an array of ids but rather the entire objects.    
   
API documentation will be updated to reflect this once the feature has been finalised   
   
@Marenthyu @itssimple
