### ISSUE TITLE
Integrate Marenthyu's Certificate generator to API user page

### ISSUE THREAD

**Issue by kenneaal** [FuelRats/api.fuelrats.com#152]
* Move Marenthyu's x509 certificate generator to a FuelRats host. 
* Add link on user's page to run generation and download the certificate. Store the FP and maybe even add it to NickServ? (If possible, it may be NS requires you to have the certificate active on the connection to add a fingerprint)

**Comment by Marenthyu** [comment]
I can modify the script to store the FP if needed. Also be aware that the script uses zsh, which i am unsure of if it is installed on the api server.

**Comment by xlexi** [comment]
the api server has zsh don't worry, I don't go anywhere without it :P 
It requires very little work for me to merely store the FP in the SQL database, just hand the script to me on IRC and I'll throw something together

**Comment by Marenthyu** [comment]
doing so

**Comment by xlexi** [comment]
Since this is a user interface realted issue I am moving it to the fuelrats.com repository, fuelrats/fuelrats.com#7
