### ISSUE TITLE
Generate channels.conf from API database entries

### ISSUE THREAD

**Issue by kenneaal** [FuelRats/api.fuelrats.com#159]
The API admin panel should include the ability to add and remove allowed channels from the IRCD.
These changes should be applied by generating a new channels.conf file and pushing it to the main IRCD server.

The format for the file is as follows:

deny channel {
        channel "*";
        reason "Creating channels is not allowed on the Fuel Rats IRC network. This is a private network; please go to a public network for your own IRC needs. Contact an Oper if you are a Fuel Rat and have a need for a channel to be created.";
        class "clients";
        warn on;
        redirect "#channel-requests";
};

allow channel {
        channel "#fuelrats";
        channel "#RatChat";
        channel "#DrillRats";
[....]
};

**Comment by xlexi** [comment]
Originally from fuelrats/api.fuelrats.com#6

**Comment by xlexi** [comment]
Since this is a user interface based feature I will move this issue to the website repository, fuelrats/fuelrats.com#6
