### ISSUE TITLE
Generic 500 on POST /rats

### ISSUE THREAD

**Issue by Marenthyu** [FuelRats/api.fuelrats.com#165]
This should be creating a new Rat, and it does, but it responds with a generic 500:

post body:
`{
	"CMDRname":"MarenSmurf",
	"platform":"pc"
}`

response: 
`{
  "errors": [
    {
      "error": {
        "code": 500,
        "detail": {},
        "status": "Internal Server Error",
        "title": "Server Error"
      },
      "meta": {}
    }
  ],
  "links": {
    "self": "/rats"
  },
  "meta": {
    "method": "POST",
    "params": {
      "CMDRname": "MarenSmurf",
      "platform": "pc"
    },
    "timestamp": "2016-09-07T12:50:20.758Z"
  }
}`

**Comment by xlexi** [comment]
resolves
