### ISSUE TITLE
POST /users/id not updating CMDRs array

### ISSUE THREAD

**Issue by Marenthyu** [FuelRats/api.fuelrats.com#166]
This should add a rat to a user's account (or rather update the user's rats with the given array):
POST /user/id
Body: `{
	"CMDRs":["0c4470d5-0cae-4b45-b67b-664d3409d23b", "1f4470d5-0cae-4b45-b67b-664d3409d23b"]	
}`

response:
`{
  "data": {},
  "links": {
    "self": "/users/c5ff3ef1-4351-41b8-9565-77105bec4c98"
  },
  "meta": {
    "method": "POST",
    "params": {
      "CMDRs": [
        "0c4470d5-0cae-4b45-b67b-664d3409d23b",
        "1f4470d5-0cae-4b45-b67b-664d3409d23b"
      ]
    },
    "timestamp": "2016-09-07T12:58:26.183Z"
  }
}`

The user remains unchanged. Response status code is 200 OK

**Comment by xlexi** [comment]
POST /users/id is not a valid endpoint. POST is for creation not updating, if you wish to update an existing user use PUT

**Comment by Marenthyu** [comment]
my bad.
