### ISSUE TITLE
Allow the paperwork to be autopopulated if the route contains an id

### ISSUE THREAD

**Issue by trezy** [FuelRats/api.fuelrats.com#23]

**Comment by xlexi** [comment]
Prefill first limpet field in edit rescue with the first rat owned by the user on the relevant platform

**Comment by dewiniaid** [comment]
Rather than the first owned rat, this should probably be:
* Whichever of the assigned rats belongs to that user, if any, or
* Their currentRat (or whatever format that currently is in)

**Comment by xlexi** [comment]
Right of course, that makes a lot more sense, didn't even occur to me that this information would be available
