### ISSUE TITLE
POST /api/rescues/ should NOT fall back to GET /api/rescues/

### ISSUE THREAD

**Issue by tyrope** [FuelRats/api.fuelrats.com#3]
[as shown in this test](http://ix.io/mbW/python) made by @duk3luk3, a POST to /api/rescues with an invalid syntax acts like a GET. This should never occur.

As such, it might be a good idea to instead require the POST to be on a different endpoint, like /api/rescues/new ?

**Comment by trezy** [comment]
The issue with this was strange. All I had to do was reorder the method chain for each endpoint and now invalid responses will receive errors correctly. The odd part is that the ordering shouldn't matter. I'm just leaving a comment about this in case we see the issue again in the future.
