### ISSUE TITLE
Add HTTPS endpoint

### ISSUE THREAD

**Issue by trezy** [FuelRats/api.fuelrats.com#37]
This should be as simple as requiring the `https` module and adding another listener for it.

**Comment by itssimple** [comment]
[security certificate is from localhost.daplie.com #12](https://github.com/Daplie/letsencrypt-express/issues/12)

The author of [letsencrypt-express](https://github.com/Daplie/letsencrypt-express) still has an open issue about the certificates not changing as they should. But in the comments, there are suggestions on how to come past this, 
I will try to implement one of the solutions for this.

**Comment by trezy** [comment]
I'm gonna go ahead and close this issue for now since it's technically done. You can open another one if you'd like.
