### ISSUE TITLE
rescue.platform fails validation when set to null

### ISSUE THREAD

**Issue by dewiniaid** [FuelRats/api.fuelrats.com#52]
When sending data for a rescue, the API complains if platform is null.

We should probably allow platform to be null rather than defaulting it to PC, as there needs to be a clear way to indicate "We don't yet know what platform this client is on".

**Comment by kenneaal** [comment]
Should not be null unless the enum specifically has a null in it. Defaulting to PC is what we do mentally as well. :P

[--- Commented from Asana.com
#commenter Kenneth Aalberg
---[aa]

**Comment by dewiniaid** [comment]
We mentally default to PC yes, but I think there should be a difference
between "They didn't tell us the platform so we're assuming PC" and "We're
certain this is PC, probably because they told us."

Dispatchers SHOULD set the platform, but that isn't guaranteed to always
happen and it's better for someone to see "unknown platform" with quoting a
case and have to ask than assuming an xbox case is PC just because the
dispatcher forgot to change it.

Additionally, the Mecha build I'm currently testing attempts some
autodetection: If the first line(s) of a new case matches `\bpc\b`, the
case is flagged as PC; if it matches `\bxb(ox|one|1)?\b` it's fledged as
XBox.  There's a tiny chance of false positives (I haven't tested something
like `Alrai Sector PC-J D4` against it yet) but it should be so low as to
never affect things -- and it can always be overridden anyways.

It platform is allowed to be null, this detection can be extended to *any*
line added to a case if the case's platform isn't already set.
