### ISSUE TITLE
Install URL shortener

### ISSUE THREAD

**Issue by kenneaal** [FuelRats/api.fuelrats.com#53]
We could really use that URL shortener active, to put the KGBFOAM link and such in there now.
API connection? If not feasible in short time, just make it a shortener that works, so we can replace the bit.ly links and get Mecha 1's !facts updated.

Orange_Sheets: Go through !facts list and see if more needs to be added, based on what the rats have been using their scripts/bots for in chat sofar.

**Comment by kenneaal** [comment]
Orange, poke regarding this task.

[--- Commented from Asana.com
#commenter Kenneth Aalberg
---[aa]

**Comment by kenneaal** [comment]
Lapotor-bot's stuff is:

20:05 <Orange_Sheets> Lapotor
20:05 <Lapotor[BOT]> ==========HELP [BOT]Lapotor==========
20:05 <Lapotor[BOT]> !newrat => has a couple of links for new rats (can't not used in #FuelRats)
20:05 <Lapotor[BOT]> !scoop => has the alternativ link for !kgbfoam (can only used in #FuelRats)
20:05 <Lapotor[BOT]> !db => gives the link for the DB guide (works only in #DrillRats)
20:05 <Lapotor[BOT]> !update = show updates of [BOT]Lapotor (don't work in #FuelRats)
20:05 <Lapotor[BOT]> !help => show this + mechasqueak's help
20:05 <Lapotor[BOT]> PM without '!'
20:05 <Lapotor[BOT]> -------------------------------------
20:05 <Lapotor[BOT]> Please have a look to info (use /msg mechasqueak[BOT] quote 1)
20:05 <Orange_Sheets> update
20:05 <Lapotor[BOT]> ==========UPDATES==========
20:05 <Lapotor[BOT]> Respons on PM's => In DONE
20:05 <Lapotor[BOT]> Set names behind an command for the output
20:06 <Orange_Sheets> db
20:06 <Lapotor[BOT]> The debrief guide => http://goo.gl/VT6qyc
20:06 <Orange_Sheets> scoop
20:06 <Lapotor[BOT]> To learn about Filtering the Galaxy Map click here: http://fuelrats.com/wp-content/uploads/2015/10/FilteringScoopables_instructions.jpg
20:06 <Orange_Sheets> newrat
20:06 <Lapotor[BOT]> Here are the most important links for newrats => 1. http://goo.gl/UXt8Ic l 2. http://goo.gl/kZ21WC l 3. http://goo.gl/3S8p8I l 4. http://goo.gl/1J1F6b l 5.
                     http://goo.gl/4Y7QNB l 6. http://goo.gl/mDF03t

[--- Commented from Asana.com
#commenter Orange Sheets
---[aa]

**Comment by kenneaal** [comment]
Apparently people like the newrats, so that could go in.

[--- Commented from Asana.com
#commenter Orange Sheets
---[aa]

**Comment by kenneaal** [comment]
I still think that throwing a half dozen links at people using a bot command isn't how we introduce them to ratting. If we want them to read up on some material, curate links into the how-to-rat page, and link them there only. !newrat (I suggest !howtorat) could show that link.
The other commands are a bit redundant, IMO. The debrief guide belongs under how to rat, !scoop is there simply because the bit.ly link fails for some people.

[--- Commented from Asana.com
#commenter Kenneth Aalberg
---[aa]

**Comment by trezy** [comment]
:+1: to @kenneaal

**Comment by xlexi** [comment]
I'd like more information on how the url shortener should work, should it be a generic available page that anyone can use, like bit.ly, should it require login? should it only be available via API?

**Comment by xlexi** [comment]
<Absolver> In other news, regarding the shortener - we can do a page for adding shortened URLs behind authentication when we get to that. Until then, let's make it API generated with an obscure URL for us to add without going through API?
