### ISSUE TITLE
Assign/Unassign complexities

### ISSUE THREAD

**Issue by dewiniaid** [FuelRats/api.fuelrats.com#55]
It looks like the current API has rats as a list of rat IDs, and unidentifiedRats to be a list of names.  Here's some potential headaches I'm seeing with that:

* When assigning rats to a case, Mecha's process requires an API call to try to find the rat being assigned and only then determining whether they're identified or not.

* IRC nicknames are (will be) per-user, not per-rat, so they can't be definitively mapped to an individual rat.  This can be limited somewhat by platform, but not 100% and the platform isn't already known at time of !assign.

* When retrieving a case, a separate API call is currently required to lookup all of the assigned rats on a case.

Because of the nicknames bit (and the fact that someone with multiple CMDRs might swap accounts based on what's closer), I almost think the best course of action is to have the 'rats' field refer to users, rather than rats.

If we do that: We can implement a way for a user (or Mecha by proxy) to specify *which* rat they currently are.  Various things that reference this can handle the transition from user to rat.

Otherwise: If we implement that same notion of identity management, searches by nickname can just default to what rat the user currently is.  The only problem here is the oddness required in correcting it.

**Comment by trezy** [comment]
Fortunately all of these issues are easily addressed.

> When assigning rats to a case, Mecha's process requires an API call to try to find the rat being assigned and only then determining whether they're identified or not.

Mecha doesn't need to make that determination. The API actually makes that call for you. You can add whatever you have to the `rats` field whether it's an ID, a CMDR name, or an entire rat object. The API will inspect all of the items in the list before saving and either convert them to IDs or push them to the `unidentifiedRats` field if they don't exist in the API.

> IRC nicknames are (will be) per-user, not per-rat, so they can't be definitively mapped to an individual rat. This can be limited somewhat by platform, but not 100% and the platform isn't already known at time of !assign.

IRC nicks will be per user, yeah, but they can indeed be mapped to an individual rat. Each rat has a `user` field which references the user with which the rat is associated. I don't think that field is currently populated on request but it should be.

> When retrieving a case, a separate API call is currently required to lookup all of the assigned rats on a case.

That shouldn't be true. The bulk GET endpoint returns a list of rescues, each with a `rats` field full of rat IDs. However the if you hit the GET endpoint with the rescues ID it should return with the `rats` field fully populated.

> ...I almost think the best course of action is to have the 'rats' field refer to users, rather than rats.

We already have refs available for all of the necessary data. See above.

> We can implement a way for a user (or Mecha by proxy) to specify which rat they currently are.

Definitely not. You're now requiring all rats to set their active rat. That's an extra step that shouldn't be required. Our goal with all of our projects is to make things *easier* for rats to do their jobs.
