### ISSUE TITLE
Summary data (Reporting) based on date range

### ISSUE THREAD

**Issue by itssimple** [FuelRats/api.fuelrats.com#58]
> &lt;Orange_Sheets&gt; I would like to do some kind of weekly digest reports from the data with the new platform.
> &lt;Orange_Sheets&gt; Or monthly reports.

Shouldn't be too hard to implement.

Could return something like:
`{ rescues: { success: 100, failure: 1 }, dateRange: { start: '2016-01-01T00:00:00+0000', end: '2016-01-31T23:59:59+0000' } }`

**Comment by kenneaal** [comment]
Actually this can be / is satisfied with proper stats/leaderboard view. I got schemas for it on a postIt, will wireframe them up soon(tm).

[--- Commented from Asana.com
#commenter Orange Sheets
---[aa]

**Comment by xlexi** [comment]
I agree this should be implemented in the leaderboards. I am merging this issue with #22, further discussion on this issue should continue there
