### ISSUE TITLE
Link Leaderboard to EDSM/similar

### ISSUE THREAD

**Issue by Burwellian** [FuelRats/api.fuelrats.com#59]
Allow the leaderboard to compare systems of rescues with EDSM or similar database and by extension pull the distance of that rescue from Sol or Fuelum if the system co-ords are known.

This allows an auto updating list of furthest rescues and Epic rescues.

**Comment by trezy** [comment]
So I'm not opposed to this but there are a couple of issues:

1. EDSM has a zero second API that we could utilize to make those calculations. However, they have less than 1% of the systems in E:D, making it unlikely that we'd be able to make those calculations.

1. Where do we make those calculations from? We're not currently storing the data for where a rat started at. Even more difficult, we'd need to get the starting point for every rat that assisted.

## Enter RatTracker

EDSM would definitely benefit from RatTracker integration. If it automatically stuffed all of the coords it gathers into EDSM it'd be a huge boon. However, it'd be far more beneficial for RT to make those calculations as the rat jumps from system to system and stores that data in the API once the rat reaches the client. That'd make it easy for us to track the distance travelled by each rat.

**Comment by Burwellian** [comment]
My understanding from recent discussions were that epicness is measured from the bubble, e.g. from Sol, as even if a Rat is already out there, they had to get out there in the first place?

Of the current top 20 systems for furthest rescues, more than half are known to EDSM, and I intend to plot the rest on my way to Beagle Point (assuming I ever get there).

Certainly wouldn't object if RatTracker can do this sort of thing better though. :)

**Comment by kenneaal** [comment]
RatTracker can't actually deduce the exact coordinates for a system at the moment - at least we don't think so. The 64-bit integers that represent body positions which we see when entering the system are not galactic grid coordinates. The best RatTracker could do is integrate what EDDiscovery2 does, and allow for trilateration of systems.

What RatTracker does at present is when a client arrives and their system is revealed, a query is made to EDSM looking for first their exact system. If it has that system's coordinates, an exact distance from the rat's current system (or most recently visited system with coordinates, if the current system doesn't have coords) is shown. If the exact match can't be found, another search fetches the entire sector data, and then starts widening the search, in the hopes that at least ONE starsystem in the sector has coordinates.
With this search, a maximum deviation of 1 cubic KLy is possible. However, for the purposes of the API storing system distance with the intent of being a tool for determining epic rescue distances, an exact coordinate would be needed.

Of course, you could encourage rats to trilaterate their epic rescue systems, thus providing the data needed, but I doubt the majority of them will be doing it.

**Comment by dewiniaid** [comment]
>  The best RatTracker could do is integrate what EDDiscovery2 does, and allow for trilateration of systems.

Which would be overkill IMHO.  EDDiscovery2 is designed around trilaterating, we shouldn't be reinventing the wheel.  If there's a desire to trilaterate, people can grab EDDiscovery2. ;)
