### ISSUE TITLE
Provide /user endpoint for account management

### ISSUE THREAD

**Issue by kenneaal** [FuelRats/api.fuelrats.com#61]
We have no way of adding data to the owner model, such as which rats belong to the account and soforth.

This might be handy.

**Comment by xlexi** [comment]
This endpoint will most likely be named /user as that is the terminology used for it within the models.
What holds this back the most is the requirement for authentication so people can not mess with other peoples accounts.     

This is already implemented in HTTP, but the websocket currently has no authentication system.



I kind of depend on #7 before I can implement this in websocket, would an HTTP only endpoint for /user be ok for now?

**Comment by kenneaal** [comment]
Yes, a HTTP endpoint is fine. This is mostly to get ratIDs and account info into RT in a sane manner.

**Comment by xlexi** [comment]
If you only need read-only, this could be implemented in websocket without complications

**Comment by kenneaal** [comment]
RT doesn't need to write anything to the API (beyond messages) at this point.

**Comment by xlexi** [comment]
Alright, read only endpoint for /user will be provided soon enough for both HTTP and websocket then.

**Comment by xlexi** [comment]
I have added a read-only /user/ endpoint for both HTTP and websocket in the websocket-api branch, for this to work you will need to drop the database and run the import script again.

I'm keeping this issue open until write apis are finished

**Comment by xlexi** [comment]
completed
