### ISSUE TITLE
Create rescue form for client before entering IRC

### ISSUE THREAD

**Issue by xlexi** [FuelRats/api.fuelrats.com#85]

**Comment by xlexi** [comment]
<Absolver[PC]> But basically, what I'm thinking is as above. We have the landing page form, with commander name, system name, platform and code red status. Its only output to the actual web client is a 301 redirect header, with the URL containing GET vars that prefills the KiwiIRC form. That way, 
23:45:23 Absolver[PC] we can hide the fields and just leave a Connect button.

**Comment by itssimple** [comment]
This is fixed, right?

**Comment by xlexi** [comment]
yes
