### ISSUE TITLE
PW issue:cannot sumbit

### ISSUE THREAD

**Issue by LetsGeiloLp** [FuelRats/api.fuelrats.com#86]
I cant sumbit on  PW,i inserted my name and stuff but it says under "who fired the first limpet" "Insert a Value".PLS HELP

**Comment by xlexi** [comment]
You need to select your name in the dropdown that appears so your name gets turned into a 'tag'.

**Comment by LetsGeiloLp** [comment]
I did,thats why i am asking for help

**Comment by xlexi** [comment]
Can you please submit a screenshot of the paperwork form with this error visible
