### ISSUE TITLE
Officially assign a meta field as a 'echos back to client' field

### ISSUE THREAD

**Issue by dewiniaid** [FuelRats/api.fuelrats.com#98]
Currently, it's possible to specify arbitrary attributes of `meta` in a request and get them returned exactly-as-is using the websocket API.

Would it be possible to specifically assign a "This is the meta attribute you should be using for that purpose" for the sake of future compatibility?  The primary goal here is to help async client code track which response is associated with which request by means of assigning a unique ID to each request.

Original conversation:
```
<Dewin> xlexious: Is there anything I can put in meta: {}  that will be echoed back?
<xlexious> Dewin: anything
<Dewin> so it's ignored by the API entirely and just repeated?
<xlexious> you can put any arbitrary info in the meta and it should be echoed back
<Dewin> Alright.  Awesome.
<xlexious> not entirely, some fields like action and reserved by the API and will overwrite whatever you send
<xlexious> thank Absolver, he requested this feature earlier
<Dewin> in that case, I'm going to open an issue to officially reserve a meta field for that purpose.
```

**Comment by xlexi** [comment]
I recommend using the field name 'callback', and guarantee it will not be reserved or modified by the API

**Comment by dewiniaid** [comment]
`callback` seems like it dictates a specific purpose clientside, `client_data` might be be more generic though I'm not entirely happy with that either.  Maybe `return` or `reply_with`?

(Alternatively, we can reserve an entire prefix ala HTTP `x-whatever` headers, though we probably don't want to use '-' for reasons of of Javascript-based clients)

**Comment by xlexi** [comment]
'return' sounds like a good idea. I'd prefer not to go the prefix route unless I was going to make it only possible to include data with prefix

**Comment by dewiniaid** [comment]
In a perfect world, we should probably be reasonably strict with API requests anyways -- I'd rather an error message telling me the API has no idea what `limti` means instead of trying to figure out why it's ignoring my attempts at specifying a limit.

But that argument applies regardless of whether we choose a prefix or `return`

**Comment by xlexi** [comment]
Realistically the API is never going to return an error ofr unknown meta fields, in actions like rescue:read, meta tags are used for search filters, and such an error system would involve each function maintaining a list of every acceptable field (which in the case of functions that uses elasticsearch search filtering, can be in the hundreds)

**Comment by kenneaal** [comment]
IMO, meta tags should never cause errors from the API, be it 3PA message or a request against normal endpoints. The meta fields are supposed to be extra processing information used by endpoints that care about them, and 3PA. Statefulness should be enforced on the query body and arguments, though.
